version: '3'
services:
  mean-stack-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/app/
  mean-stack-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/dist:/usr/src/app/client/dist
  mean-stack-database:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    ports:
      - "27017:27017"
