version: '3'
services:
  mean-stack-client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./:/usr/src/app/
  mean-stack-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app/server
      - ./client/dist:/usr/src/app/client/dist
    entrypoint:
      - npm
      - run
      - dev
  mean-stack-database:
    image: mongo
    ports:
      - "27017:27017"
  mean-stack-database-seed:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    command:
      "/bin/sh seed-database.sh"
