version: '3'

services:
  mean-stack:
    image: mean-stack
    build: .
    working_dir: /usr/src/app/server
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
       - ./server/dist:/usr/src/app/server/dist
    command: npm run start:dev
  mean-stack-database:
    image: mongo
    ports:
      - "27017:27017"
  mean-stack-database-seed:
    build:
      context: ./database
      dockerfile: ./Dockerfile
