version: '2.1'

services:
  mean-stack
    image: mean-stack
    build: .
    env_file:
      - .env
    # environment:
    #   NODE_ENV: development
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start:dev
    # command: node --inspect=0.0.0.0:9229 server.js
