version: '3'

services:
  mean-stack:
    image: mean-stack
    build: .
    working_dir: /usr/src/app/server
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    command: npm run start
  mean-stack-database:
    image: mongo
    ports:
      - "27017:27017"
  mean-stack-database-seed:
    build:
      context: ./database
      dockerfile: ./Dockerfile
