Vagrant.configure(2) do |config|
        # - set the image to be used to be ubuntu/zesty64
        # - set the hostname of the machine
        # - do not check for base image updates
        # - do not sync the default vagrant directory
        config.vm.box = "ubuntu/xenial64"
        config.vm.box_version = "20180627.0.0"
        # config.vm.box = "ubuntu/trusty64"
        config.vm.hostname = "test-machine"
        config.vm.box_check_update = false
        config.vm.synced_folder ".", "/vagrant", disabled: true
        config.vm.network "private_network", ip: "172.30.1.5"
        config.vm.network "forwarded_port", guest: 3000, host: 3000


        # - configure some parameters from the virtualbox provider
        config.vm.provider "virtualbox" do |v|
                v.memory = 1024
                v.cpus = 1
        end


        # hook ansible into the process of provisioning
        # the machine.
        # -     using the ansible configuration file
        #       located at `../ansible/ansible.cfg`,
        #       execute the playbook at `playbooks/provision-vagrant.yml`
        config.vm.provision "ansible" do |ansible|
                ansible.limit = "all,localhost"
                ansible.config_file = "../ansible/ansible.cfg"
                ansible.playbook = "../ansible/site.yml"
        end
end
